telemonitoreo:
    resource: "@TelemonitoreoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_bundle:
    resource: "@AppBundle/Resources/config/persona.yml"
    prefix: /

telemonitoreo_historiaclinica:
    resource: "@TelemonitoreoBundle/Resources/config/historiaclinica.yml"
    prefix: /

telemonitoreo_equipomedico:
    resource: "@TelemonitoreoBundle/Resources/config/equipomedico.yml"
    prefix: /