telemonitoreo:
    resource: "@TelemonitoreoBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

app_bundle:
    resource: "@AppBundle/Resources/config/persona.yml"
    prefix: /

telemonitoreo_historiaclinica:
    resource: "@TelemonitoreoBundle/Resources/config/historiaclinica.yml"
    prefix: /

telemonitoreo_equipomedico:
    resource: "@TelemonitoreoBundle/Resources/config/equipomedico.yml"
    prefix: /

telemonitoreo_variableclinica:
    resource: "@TelemonitoreoBundle/Resources/config/variableclinica.yml"
    prefix: /

telemonitoreo_historicos:
    resource: "@TelemonitoreoBundle/Resources/config/historicos.yml"
    prefix: /

telemonitoreo_registro:
    resource: "@TelemonitoreoBundle/Resources/config/registro.yml"
    prefix: /

telemonitoreo_parametro:
    resource: "@TelemonitoreoBundle/Resources/config/parametro.yml"
    prefix: /

telemonitoreo_variablehaspaciente:
    resource: "@TelemonitoreoBundle/Resources/config/variablehaspaciente.yml"
    prefix: /

telemonitoreo_variablehasequipo:
    resource: "@TelemonitoreoBundle/Resources/config/variablehasequipo.yml"
    prefix: /

telemonitoreo_usuariohaspaciente:
    resource: "@TelemonitoreoBundle/Resources/config/usuariohaspaciente.yml"
    prefix: /

telemonitoreo_usuario:
    resource: "@TelemonitoreoBundle/Resources/config/usuario.yml"
    prefix: /